export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  CHANGE_LOADER: "CHANGE_LOADER",
  DELETE_MOVIE: "DELETE_MOVIE",
  CHANGE_IDS: "CHANGE_IDS",
  SAVE_MDF250IDS: "SAVE_MDF250IDS",
  TOGGLE_SEARCH: "TOGGLESEARCH",
};
